config/routes.rb
Rails.application.routes.draw do
  root 'page#home'

  scope format: false do
    get 'page/home'

    resources :people
    resources :clients do
      resources :contacts, except: [:index]
      resources :invoices
    end
  end

end

app/models/person.rb
class Person < ActiveRecord::Base
  validates_presence_of :name, :cuilt
  validates :name,
    length: { in: 2..50 },
    format: { with: /\A[A-zñÁÉÍÓÚáéíóúü][A-zñáéíóúÁÉÍÓÚü'\ ]+\z/ }
  validates :cuilt,
    length: { is: 13 },
    format: { with: /\A[0-9]{2}-[0-9]{8}-[0-9]\z/ },
    uniqueness: true

  def to_s
    "#{cuilt} #{name}"
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  def index
    @people = Person.all
  end

  # GET /people/1
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  def create
    @person = Person.new(person_params)

    if @person.save
      redirect_to @person, notice: t("created_person")
    else
      render :new
    end
  end

  # PATCH/PUT /people/1
  def update
    if @person.update(person_params)
      redirect_to @person, notice: t("erased_person")
    else
      render :edit
    end
  end

  # DELETE /people/1
  def destroy
    @person.destroy
    redirect_to people_url, notice: t("updated_person")
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def person_params
      params.require(:person).permit(:name, :cuilt)
    end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form.html.erb
<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, t("active_record.attributes.person.name") %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :cuilt, t("active_record.attributes.person.cuilt") %><br>
    <%= f.text_field :cuilt %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1><%= t("edit_person") %></h1>

<%= render 'form' %>

<%= link_to t("show"), @person %> |
<%= link_to t("back"), people_path %>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= t("listing_people") %></h1>

<table>
  <thead>
    <tr>
      <th><%= t("active_record.attributes.person.name") %></th>
      <th><%= t("active_record.attributes.client.cuilt") %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.name %></td>
        <td><%= person.cuilt %></td>
        <td><%= link_to t("show"), person %></td>
        <td><%= link_to t("edit"), edit_person_path(person) %></td>
        <td><%= link_to t("destroy"), person, method: :delete, data: { confirm: t("are_you_sure") } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t("new_person"), new_person_path %>

app/views/people/new.html.erb
<h1><%= t("new_person") %></h1>

<%= render 'form' %>

<%= link_to t("back"), people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%= t("active_record.attributes.person.name") %>:</strong>
  <%= @person.name %>
</p>

<p>
  <strong><%= t("active_record.attributes.client.cuilt") %>:</strong>
  <%= @person.cuilt %>
</p>

<%= link_to t("edit"), edit_person_path(@person) %> |
<%= link_to t("back"), people_path %>