config/routes.rb
Rails.application.routes.draw do
  root 'page#home'

  scope format: false do
    get 'page/home'

    resources :people
    resources :clients do
      resources :contacts, except: [:index]
      resources :invoices
    end
  end

end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  belongs_to :client
  belongs_to :person

  default_scope { order(emission_date: :desc) }

  validates_presence_of :client, :person, :description, :amount, :emission_date
  # validates_existence_of :client, :person
  validates :description,
    length: { in: 2..255 }
  validates :amount,
    numericality: {
      greater_than_or_equal_to: 0,
      less_than_or_equal_to: 9999999999.99
    }
  validates :emission_date,
    date: { before: Proc.new { Time.now + 1.day } }
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: [:show, :edit, :update, :destroy]
  before_action :set_client

  # GET /invoices
  def index
    @invoices = Invoice.all
  end

  # GET /invoices/1
  def show
  end

  # GET /invoices/new
  def new
    @invoice = Invoice.new
  end

  # GET /invoices/1/edit
  def edit
  end

  # POST /invoices
  def create
    @invoice = Invoice.new(invoice_params)

    if @invoice.save
      redirect_to client_invoice_url(@client, @invoice), notice: t("created_invoice")
    else
      render :new
    end
  end

  # PATCH/PUT /invoices/1
  def update
    if @invoice.update(invoice_params)
      redirect_to client_invoice_url(@client, @invoice), notice: t("erased_invoice")
    else
      render :edit
    end
  end

  # DELETE /invoices/1
  def destroy
    @invoice.destroy
    redirect_to client_invoices_url(@client), notice: t("updated_invoice")
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    def set_client
      @client = Client.find(params[:client_id])
    end

    # Only allow a trusted parameter "white list" through.
    def invoice_params
      params.require(:invoice).permit(:client_id, :person_id, :description, :amount, :emission_date)
    end
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/invoices/_form.html.erb
<%= form_for([@client, @invoice]) do |f| %>
  <% if @invoice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@invoice.errors.count, "error") %> prohibited this invoice from being saved:</h2>

      <ul>
      <% @invoice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :client_id, t("active_record.attributes.invoice.client") %><br>
    <%= f.select :client_id, [[@client, @client.id]] %>
  </div>
  <div class="field">
    <%= f.label :person_id, t("active_record.attributes.invoice.person") %><br>
    <%= f.select :person_id, Person.find_each(batch_size: Person.count).map { |p| [p, p.id] }, { include_blank: t(:select_person) } %>
  </div>
  <div class="field">
    <%= f.label :description, t("active_record.attributes.invoice.description") %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :amount, t("active_record.attributes.invoice.amount") %><br>
    <%= f.text_field :amount, placeholder: t("amount_example") %>
  </div>
  <div class="field">
    <%= f.label :emission_date, t("active_record.attributes.invoice.emission_date") %><br>
    <%= f.date_select :emission_date, start_year: Time.now.year - 150, end_year: Time.now.year, default: Time.now %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/invoices/edit.html.erb
<h1><%= t("edit_invoice") %></h1>

<%= render 'form' %>

<%= link_to t("show"), client_invoice_path(@client, @invoice) %> |
<%= link_to t("back"), client_invoices_path(@client) %>

app/views/invoices/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= t("listing_invoices") %></h1>

<h2><%= "#{Client.model_name.human}: #{@client}" %></h2>

<% if @client.has_invoices %>
  <table>
    <thead>
      <tr>
        <th><%= t("active_record.attributes.invoice.emission_date") %></th>
        <th><%= t("active_record.attributes.invoice.person") %></th>
        <th><%= t("active_record.attributes.invoice.description") %></th>
        <th><%= t("active_record.attributes.invoice.amount") %></th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @client.invoices.each do |invoice| %>
        <tr>
          <td><%= invoice.emission_date %></td>
          <td><%= invoice.person.name %></td>
          <td><%= invoice.description %></td>
          <td><%= number_to_currency(invoice.amount) %></td>
          <td><%= link_to t("show"), client_invoice_path(@client, invoice) %></td>
          <td><%= link_to t("edit"), edit_client_invoice_path(@client, invoice) %></td>
          <td><%= link_to t("destroy"), client_invoice_path(@client, invoice), method: :delete, data: { confirm: t("are_you_sure") } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p><%= t :client_has_no_invoices %></p>
<% end %>

<%= link_to t("new_invoice"), new_client_invoice_path(@client) %><br><br>

<%= link_to "#{t("back_to_client")} #{@client.last_name}, #{@client.first_name}", client_path(@client) %> |
<%= link_to t("back_to_clients_index"), clients_path %>

app/views/invoices/new.html.erb
<h1><%= t("new_invoice") %></h1>

<%= render 'form' %>

<%= link_to t("back"), client_invoices_path(@client) %>

app/views/invoices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%= t("active_record.attributes.invoice.client") %>:</strong>
  <%= @invoice.client %>
</p>

<p>
  <strong><%= t("active_record.attributes.invoice.person") %>:</strong>
  <%= @invoice.person %>
</p>

<p>
  <strong><%= t("active_record.attributes.invoice.description") %>:</strong>
  <%= @invoice.description %>
</p>

<p>
  <strong><%= t("active_record.attributes.invoice.amount") %>:</strong>
  <%= @invoice.amount %>
</p>

<p>
  <strong><%= t("active_record.attributes.invoice.emission_date") %>:</strong>
  <%= @invoice.emission_date %>
</p>

<%= link_to t("edit"), edit_client_invoice_path(@client, @invoice) %> |
<%= link_to t("back"), client_invoices_path(@client) %>