config/routes.rb
Rails.application.routes.draw do
  root 'page#home'

  scope format: false do
    get 'page/home'

    resources :people
    resources :clients do
      resources :contacts, except: [:index]
      resources :invoices
    end
  end

end

app/models/client.rb
class Client < ActiveRecord::Base
  has_many :contacts, dependent: :destroy
  has_many :invoices, dependent: :destroy
  has_many :people, through: :invoices

  enum gender: %i(female male)

  validates_presence_of :first_name, :last_name, :document_number, :gender, :birthday, :cuilt
  validates :first_name, :last_name,
    length: { in: 2..50 },
    format: { with: /\A[A-zñÁÉÍÓÚáéíóúü][A-zñáéíóúÁÉÍÓÚü'\ ]+\z/ }
  validates :document_number,
    length: { in: 1..8 },
    format: { with: /\A[0-9]+\z/ },
    uniqueness: true
  validates :cuilt,
    length: { is: 13 },
    format: { with: /\A[0-9]{2}-[0-9]{8}-[0-9]\z/ },
    uniqueness: true
  validates :birthday,
    date: { before: Proc.new { Time.now + 1.day } }
  validates_associated :contacts
  validates_associated :invoices

  def to_s
    "#{document_number} - #{last_name}, #{first_name}"
  end

  def age
    age = Date.current.year - birthday.year
    age -= 1 unless
      Date.current.month >= birthday.month &&
      Date.current.day >= birthday.day
    age
  end

  def has_invoices
    invoices.size > 0
  end

  def total_invoiced_amount
    invoices.inject(0) { |sum, i| sum + i.amount }
  end

  def total_invoiced_amount_per_year
    invoices.group("strftime('%Y', emission_date)").sum(:amount)
  end

  def has_invoices_from_january
    invoices.where("emission_date >= ?", Date.new(Time.now.year, 1, 1)).count > 0
  end

  def invoices_amount_from_january
    invoices.where("emission_date >= ?", Date.new(Time.now.year, 1, 1)).group("strftime('%m', emission_date)").count
  end

  def more_invoiced_people(amount)
    people
      .select("name, cuilt, sum(amount) as sum_amount")
      .group(:id)
      .reorder("sum_amount DESC")
      .limit(amount)
  end

  def has_contacts
    contacts.size > 0
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  def index
    @clients = Client.all
  end

  # GET /clients/1
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  def create
    @client = Client.new(client_params)

    if @client.save
      redirect_to @client, notice: t("created_client")
    else
      render :new
    end
  end

  # PATCH/PUT /clients/1
  def update
    if @client.update(client_params)
      redirect_to @client, notice: t("erased_client")
    else
      render :edit
    end
  end

  # DELETE /clients/1
  def destroy
    @client.destroy
    redirect_to clients_url, notice: t("updated_client")
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def client_params
      params.require(:client).permit(:first_name, :last_name, :document_number, :gender, :birthday, :cuilt)
    end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.erb
<%= form_for(@client) do |f| %>
  <% if @client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% @client.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name, t("active_record.attributes.client.first_name") %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name, t("active_record.attributes.client.last_name") %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :document_number, t("active_record.attributes.client.document_number") %><br>
    <%= f.text_field :document_number %>
  </div>
  <div class="field">
    <%= f.label :gender, t("active_record.attributes.client.gender") %><br>
    <%= f.select :gender, Client.genders.keys.map { |g| [t("active_record.attributes.client.genders.#{g}"), g]}, { include_blank: true } %>
  </div>
  <div class="field">
    <%= f.label :birthday, t("active_record.attributes.client.birthday") %><br>
    <%= f.date_select :birthday, start_year: Time.now.year - 150, end_year: Time.now.year, default: Time.now %>
  </div>
  <div class="field">
    <%= f.label :cuilt, t("active_record.attributes.client.cuilt") %><br>
    <%= f.text_field :cuilt %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1><%= t("edit_client") %></h1>

<%= render 'form' %>

<%= link_to t("show"), @client %> |
<%= link_to t("back"), clients_path %>

app/views/clients/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= t("listing_clients") %></h1>

<table>
  <thead>
    <tr>
      <th><%= t("active_record.attributes.client.first_name") %></th>
      <th><%= t("active_record.attributes.client.last_name") %></th>
      <th><%= t("active_record.attributes.client.document_number") %></th>
      <th><%= t("active_record.attributes.client.gender") %></th>
      <th><%= t("active_record.attributes.client.birthday") %></th>
      <th><%= t("active_record.attributes.client.cuilt") %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.first_name %></td>
        <td><%= client.last_name %></td>
        <td><%= client.document_number %></td>
        <td><%= t("active_record.attributes.client.genders.#{client.gender}") %></td>
        <td><%= client.birthday %></td>
        <td><%= client.cuilt %></td>
        <td><%= link_to t("active_record.models.invoices"), client_invoices_path(client) %></td>
        <td><%= link_to t("show"), client %></td>
        <td><%= link_to t("edit"), edit_client_path(client) %></td>
        <td><%= link_to t("destroy"), client, method: :delete, data: { confirm: t("are_you_sure") } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t("new_client"), new_client_path %>

app/views/clients/new.html.erb
<h1><%= t("new_client") %></h1>

<%= render 'form' %>

<%= link_to t("back"), clients_path %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= t("active_record.models.client") %></h1>

<h2><%= t :personal_info %></h2>
<p>
  <strong><%= t "active_record.attributes.client.first_name" %>:</strong>
  <%= @client.first_name %>
</p>

<p>
  <strong><%= t "active_record.attributes.client.last_name" %>:</strong>
  <%= @client.last_name %>
</p>

<p>
  <strong><%= t "active_record.attributes.client.document_number" %>:</strong>
  <%= @client.document_number %>
</p>

<p>
  <strong><%= t "active_record.attributes.client.gender" %>:</strong>
  <%= @client.gender %>
</p>

<p>
  <strong><%= t "active_record.attributes.client.birthday" %>:</strong>
  <%= @client.birthday %>
</p>

<p>
  <strong><%= t "active_record.attributes.client.cuilt" %>:</strong>
  <%= @client.cuilt %>
</p>

<%= link_to t("edit"), edit_client_path(@client) %>

<h2><%= t :contact_info %></h2>

<% if @client.has_contacts %>
  <table>
    <thead>
      <tr>
        <th><%= t("active_record.attributes.contact.kind") %></th>
        <th><%= t("active_record.attributes.contact.value") %></th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @client.contacts.each do |contact| %>
        <tr>
          <td><%= t("active_record.attributes.contact.kinds.#{contact.kind}") %></td>
          <td><%= contact.value %></td>
          <td><%= link_to t("show"), client_contact_path(@client, contact) %></td>
          <td><%= link_to t("edit"), edit_client_contact_path(@client, contact) %></td>
          <td><%= link_to t("destroy"), client_contact_path(@client, contact), method: :delete, data: { confirm: t("are_you_sure") } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p><%= t :client_has_no_contacts %></p>
<% end %>

<%= link_to t("new_contact"), new_client_contact_path(@client) %><br><br>

<h2><%= t "active_record.models.invoices" %></h2>
<% if @client.has_invoices %>
  <p><%= link_to t("show"), client_invoices_path(@client) %></p>
<% else %>
  <%= t :client_has_no_invoices %>
<% end %>

<h2><%= t :statistics %></h2>

<ul>
  <li><%= "#{t :client_age}: #{@client.age}" %></li>
  <li><%= "#{t :client_total_invoiced_amount_per_year}:" %></li>
    <% if @client.has_invoices %>
      <% @client.total_invoiced_amount_per_year.each do |k, v| %>
        <ul><%= "#{k} - #{number_to_currency(v)}" %></ul>
      <% end %>
    <% else %>
      <ul><%= t :client_has_no_invoices %></ul>
    <% end %>
  <li><%= "#{t :client_invoices_amount_from_january}:" %></li>
    <% if @client.has_invoices_from_january %>
      <% @client.invoices_amount_from_january.each do |k, v| %>
        <ul><%= "#{t("date.month_names")[k.to_i].capitalize} - #{v}" %></ul>
      <% end %>
    <% else %>
      <ul><%= t :client_has_no_invoices_from_january %></ul>
    <% end %>
  <li><%= "#{t :client_five_more_invoiced_people}" %></li>
    <% if @client.has_invoices %>
      <% @client.more_invoiced_people(5).each do |p| %>
        <ul><%= "#{p.name} - #{number_to_currency(p.sum_amount)}" %></ul>
      <% end %>
    <% else %>
      <ul><%= t :client_has_no_invoices %></ul>
    <% end %>
</ul>

<br>
<%= link_to t("back"), clients_path %>